### ISSUE TITLE
Question about t-states

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#12]
This is just a curiosity question, the readme for the debugger states:

> 'Scan' shows the line number (0-311) and line-cycle counter (0-383)
> 'T' shows the cycle offset within the current frame (0-119807)

So that matches up as 312 lines * 384 t-states per line = 119,808 per frame. 50 frames a second, so 50 * 119,808 = 5,990,400 = nearly 6 MHz.

Why is it not exactly 6 MHz? 

If I work backwards, then 6 Mhz / 50 frames / 384 t-states per frame = 312.5 lines - which has a familiar ring to it in combination with PAL having 625 lines.

Since simcoupe handles everything pretty perfectly, I must be missing something.

**Comment by simonowen** [comment]
The CPU runs at exactly 6MHz, so no difference will be seen from running software between real and emulated.  The apparent discrepency is because the true framerate is 50.08Hz rather than 50Hz, calculated from: 50 * 6000000 / 5990400,  That's enough that an interrupt-driven clock should run 5 seconds fast every hour. It sounds like quite a lot, but [mains frequency](https://wwwhome.ewi.utwente.nl/~ptdeboer/misc/mains.html) can vary by more than that, so any clocks using it for timing will vary too.

SimCoupe does take the true frequency into account for audio output and tape loading.  Since the audio is now used for frame synchronisation, that should mean SimCoupe runs at an average of 50.08Hz too.

**Comment by stefandrissen** [comment]
Interesting! Thanks for taking one of my true constants and bending it to 50.08 ;-)

**Comment by simonowen** [comment]
I remember it being a strange realisation, and the discussions Dave Laundon and I had over which parts of SimCoupe needed to know the difference.

It's the same frequency as the 48K Spectrum too, which has 224T * 312 lines = 69888T per frame.  3500000 / 69888 = 50.08...

**Comment by stefandrissen** [comment]
Nice! Although I am still wondering about what is true and what is fit into the equation to conveniently make it true :-)

https://www.worldofspectrum.org/faq/reference/128kreference.htm 

I would need to dive deeper into what PAL even is and how there can even be a variable number of scan lines (311 or 312) in a single frame - but being a software guy - I'm going to just believe you and try to clean up my timing routine.

**Comment by simonowen** [comment]
The receiving display largely does what its told by the synchronisation in the video signal, within certain limits.  So if the vsync always comes after 311 or 312 frames then that's the framerate.

I don't know flexible PAL is, and how tolerant TVs are expected to be, but it's only a tiny difference from true 50Hz in these cases.  I've certainly seen a number of differences what modern digital panels are willing to put up with for input signals.
