### ISSUE TITLE
Doesn't seem possible to build on Windows

### ISSUE THREAD

**Issue by stripwax** [simonowen/simcoupe#13]
Trying to build on Windows, using the VS17 project.
A fresh checkout of the source from github seems to have missing dependencies, in particular libspectrum and zlib (which is maybe fine if I know which versions to seek out and use here, but it's not obvious).  USE_ZLIB, USE_RESID and USE_LIBSPECTRUM are all #defined in the project settings, as is ZLIB_WINAPI.   Setting those all to false doesn't fix the build though, due to additional dependencies on fdrawcmd.h (which I can get from https://github.com/simonowen/fdrawcmd), d3dx9math.h (which I guess comes from the DXSDK), and zlib.h (despite setting USE_ZLIB to False).

I'm not sure if that all means the VS17 project is obsolete (and you recommend CMAKE instead), or if simcoupe is missing some build docs in the repo, or something similar.

Indications on which variant of zlib to use for Windows, and where to obtain the libspectrum.h for Windows (it doesn't seem to be in the Fuse source downloadable from http://fuse-emulator.sourceforge.net/libspectrum.php, but I found a random copy at https://github.com/ec429/spiffy/blob/master/wbits/libspectrum.h ), and/or the right way to build, might just be best.

**Comment by simonowen** [comment]
The build system does need a fairly major overhaul.  To be fair, the whole codebase needs freshening up and modernising!

I've traditionally preferred a tweaked VS build for official releases, as it gives more control over the build environment than you get with a CMake-generated project. That was an issue for avoiding CPU instructions incompatible with old systems, and for XP support, but both are less of an issue now.  A project file does have to make assumptions about dependencies available, since it doesn't have any built-in detection.  Releases come with all features enabled, so they have heavy dependency requirements, as you've found.

It sounds like fdrawcmd.h use should be conditional too, as that's only needed for real floppy support under Windows. IIRC, libspectrum.h is built when you compile libspectrum from source, which requires a Unix-like environment. ReSid was v0.16, but I think it had a 'SID' symbol that conflicted with Windows headers, and I can't remember where that was solved.

I've traditionally treated the CMake build as being non-Windows, but I think there were issues with SDL under macOS too, which may have required using Xcode.  That needs to be fixed.  I also switched to using vcpkg for standard libraries such as zlib, so it'll just expect to find those packages automatically.

I've moved to VS2019 for some other projects, and I'm hoping its CMake compatibility will make it possible to use a common file for all platforms.  I might still push a VS2019 project for official releases for the reasons above, but hopefully other people can just use CMake.

I'll re-visit the CMakeList.txt and VS2019 project and see where that takes us.  I'll gather together any dependency details as I run into them.

**Comment by simonowen** [comment]
I've had a look over the dependencies to get a feel for what's needed. The biggest problem is that some libraries need a Cygwin environment to build under Windows.  The most complicated of the current libraries is libspectrum, which uses automake to generate perl scripts, which are used to generate headers.  It's flexible from a development point of view, but means you need autogen/autoconf/automake/perl available before you can even invoke the compiler to build the library.

Even doing that, the final DLL has a Unix-style versioned name, and is linked to some multi-megabyte Cygwin runtime libraries, which I didn't want to include with a Windows release of SimCoupe.  To work around that I ran the tools under Cygwin to generate the headers, then manually created a VS project file to wrap the underlying source files.  It might have needed a few additional platform configuration tweaks. That gave a stand-alone final DLL, which is what gets included in the Windows release. Updating the underlying source files risks breaking the environment, so it's not a good long-term solution.  Though since building a working spectrum.dll (and import .lib) on my system I don't think I've touched it!

Building the dependencies under Linux and macOS is fairly trivial, since the required generation and build tools are readily available. Once the dependencies are installed (typically a one-time process) they'll be found and used by the SimCoupe build system.

Windows doesn't really have the same concept of installed development headers and libraries, which usually means relying on pre-configured paths that contain the required files. vcpkg is attempting to improve that, but you still needed to point CMake at it last time I tried, or it won't detect any optional components.  Visual Studio seems to do a better job in finding and using anything in vcpkg automatically.  vcpkg is still only good for packages that exist in their system, and that only covers zlib and bzip2 out of the current list of SimCoupe dependencies.

A good first step is to have the CMakeList.txt work in VS2019, and able to build a working Windows binary without any of the optional dependencies.  Any that are available will still be used, of course.  You'll have a fairly miserable experience without at least zlib for compressed disk images!

I've done a CMake conversion of resid, like I did for saasound. I may look into a light touch conversion of libspectrum too, if it's not too painful.  Whether they're bundled, linked as git sub-modules, etc. is something I'll ponder in the meantime.

**Comment by simonowen** [comment]
This should be resolved in 1bf2d4adbdbf0887002805b965595abc3af87862.

SimCoupe now uses CMake for building on all platforms. I've removed the project files for Visual Studio and Xcode, though you can auto-generate a project using CMake. The Open Folder approach will be easier to work with as the files in the project are changed.

The move to CMake also detects available libraries and use only those that are present. Non-Windows builds need only SDL[2], and the Windows build should work without any optional libraries. Without zlib you'll have a fairly rough experience -- get that set up through vcpkg if you haven't already!
