### ISSUE TITLE
SimCoupe 1.1 Alpha no longer supports SAASound.dll

### ISSUE THREAD

**Issue by stripwax** [simonowen/simcoupe#14]
Would it be possible to switch back to loading the SAA emulation dynamically?
More generally - what would it take to make that possible across both Windows and non-Windows implementations of SimCoupe?
(I'm happy to put the work in on the SAASound side)

**Comment by simonowen** [comment]
It moved to the self-contained version to simplify building, but that was when I thought SAASound was abandoned.  I'm happy to move it back over to using the library -- perhaps even as a git sub-module now it's on GitHub too?

**Comment by simonowen** [comment]
Fixed in c29716053c63a22e66da8341f319636c9d7f1a8b.  New SimCoupe builds after this commit will use an external SAASound library if found by CMake and configuration time.

I have a vcpkg build of SAASound, which is automatically found by Visual Studio. In the absence of that you can still point the `SAASOUND_INCLUDE_DIR` variable at the directory containing SAASound.h and the `SAASOUND_LIBRARY` at the the .lib file (import or static). To do that in Visual Studio after using Open Folder on the SimCoupe project, open `CMakeSettings.json` in the root and scroll down to the _CMake variables and cache_ section.

**Comment by stripwax** [comment]
Does that include dll support too? That's really the question here - if so
great!

**Comment by simonowen** [comment]
Yes, if the SimCoupe build finds the DLL import library (.lib) it'll use the DLL version at runtime. That should make it easy for you to drop in development builds of SAASound.dll for testing.  Let me know if you have any trouble setting it up -- you'll need a vcpkg installation for sure.

Moving SimCoupe entirely over to CMake (and work on Windows/Linux/macOS) took longer than expected, but it makes any additional development much easier.

**Comment by stripwax** [comment]
Ah gotcha. That's awesome, thanks so much!
