### ISSUE TITLE
Possible bug in z80 emulation.

### ISSUE THREAD

**Issue by sirdavid2** [simonowen/simcoupe#20]
While trying to find a bug in Sam Coupe MIST core (slightly wrong timings when a code runs from ROM or external RAM) I have found a bug in SimCoupe.  The bug  applies to CPIR/CPDR commands, which should be the same speed as LDIR, but in SimCoupe they are much faster. CPI/CPD seem ok.

**Comment by simonowen** [comment]
I've had a quick look at the code and I can't see anything that stands out as being wrong. The emulation structure of all the instructions you mention is very similar, with the repeat versions having an extra 5T added for the repeat adjustment.

I'd expect CPIR to be faster than LDIR in most cases, since it only has to read from memory. LDIR reads and writes, with each access being affected by contention delays. I _think_ the only time they'd be equal (and also matching documented Z80 timings) would be if the code is running from ROM and both DE and HL also point to ROM.

External RAM has the same timing as the border areas, where memory accesses are rounded to 4T boundaries.  LDIR will still still get stung slightly more by memory contention than CPIR.

I don't suppose you have a code sample that demonstrates the difference?

**Comment by sirdavid2** [comment]
Of course I have a code:
https://www.dropbox.com/s/c2to2l8cj4z5ttf/cpir-ldir.zip?dl=0
These are 2 disk images with the same test (it uses only internal RAM) with only 1 byte difference: CPIR or LDIR. On the real SAM they look almost the same, the lines are shifted by 1 char (so a whole LDIR and CPIR differ only by a few cycles). But on SimCoupe their positions are very different. 
Debugger says that one iteration of CPIR lasts 20 clock cycles and LDIR 24 cycles, while both should last 21 (when there are no memory/ASIC contention), so 20 should be impossible.

**Comment by simonowen** [comment]
Thanks for the samples, which were very helpful in tracking it down. All the CPD/CPI/CPIR/CPDR instructions were 3T short in the core of the instruction. The missing cycles in the non-repeat versions seemed to be masked by contention.

I've fixed it in aa3f162e52d729710b8c3c705a03e674a3686367 and uploaded a [new Windows build](https://github.com/simonowen/simcoupe/releases/tag/20200512) that includes it.
