### ISSUE TITLE
Windows function keys no longer work

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#25]
I'm using 20200819 build (updated) - none of my usual function keys work:

- F7 does not toggle motion blur
- F11 does not bring up the debugger
- F12 does not reset

But:

- F1 does open file dialog
- F4 does import data
- F5 does change aspect ratio
- F6 does change smooth image 

Maybe already solved in https://github.com/simonowen/simcoupe/commit/d4923349562110fe2bd3958bd7aba7f0192e2aff 
Maybe the result of having an older simcoupe.cfg that has not been updated?

**Comment by simonowen** [comment]
The commit in d4923349562110fe2bd3958bd7aba7f0192e2aff actually broke it, since it made the total option length much longer! Old versions of SimCoupe use a 256-byte line buffer when reading the options, which truncates the new function options, such that later keys bindings don't work.

I've already fixed it in 3e9a89959fe7c553860b622c6abbdd2ab21ff02c, which renamed the new option to avoid the conflict. The only down side is that switching between old and new versions will lose any custom mappings. I've created a [new build](https://github.com/simonowen/simcoupe/releases/tag/20200827) that includes this fix and a few other things.
