### ISSUE TITLE
simice: option to disable rom symbols

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#26]
When debugging code the symbols are really useful. However the ROM symbol table gets in the way. 

````
   ld hl,0004
   ld de,iyjump+1
````
While I can use 'S' to toggle symbols to show:
````
   ld hl,0004
   ld de,0007
````
It's just a bit annoying. 

As a workaround I can probably just delete / empty the samrom.map file and only restore it when I need it.

**Comment by simonowen** [comment]
I think I have a ToDo item somewhere to improve this, as I occasionally run into it too. Most of the time I don't have any ROMs paged in so the symbols won't resolve, but in the cases they do I tend to briefly toggle them with 'S' to check a value.

I did make some tweaks to separate value and address symbols in pyz80, which helped a little. Though there are plenty of cases where values (particularly those under 256) map to an address symbols in unwanted situations. Determining whether a value in a register is an address is a difficult problem, even with some code analysis that attempts to look ahead how the value is used.

The simplest approach I can think of is to add more context to the look-ups, so the symbol resolving can make better decisions about whether the value should be converted. In practice, there are very few data references to ROM likely from 3rd party code, so register values probably shouldn' be changed in non-ROM code. Register values used within ROM code is a bit harder to decide on, since they will sometimes mean addresses. Any CALL/JP should always be converted, as long as the ROM is paged in.

Context is going to be key, with tuning used for specific use cases. I don't think a perfect solution is possible but I'm sure it can be made good enough that most people won't notice.  I'll take a look when I get back into SimCoupe development.

**Comment by simonowen** [comment]
I've changed the matching rules so ROM symbols are only matched from outside ROM code if they're an code execution target. That should avoid the unwanted matching in user code:

![image](https://user-images.githubusercontent.com/200089/125352953-d3cdb380-e359-11eb-94d2-40c795556167.png)
