### ISSUE TITLE
SAASound in SimCoupe should probably be implemented via a submodule

### ISSUE THREAD

**Issue by stripwax** [simonowen/simcoupe#30]
It just occurred to me that other projects (e.g. RetroPie) are sourcing SimCoupe emulation directly from this repo, which contains an out-of-date build of SAASound.  Would you consider using a git submodule instead?  You could even have it as a submodule pointing to your own fork of SAASound, if that is necessary (which would have the sideeffect of making it easier to upstream any changes to your SAASound fork - since those could just be pull requests back to my master repo)

**Comment by simonowen** [comment]
SimCoupe bundles some external libraries and will use them as a fallback iff external versions aren't found. As long as SAASound is already installed somewhere CMake can find it, SimCoupe will use it in preference to the bundled version. I think SDL2 might be the only library that is _needed_ on some platforms, with everything else either optional or bundled. Hopefully it'll reduce build pain and support.

Being a sub-module would still pin it at a particular external revision, so it wouldn't always use the latest SAASound source code. I'm just updating the bundled version periodically instead of the sub-module link. Anyone wanting a specific library version just needs to install it first. Or is there a use case I'm missing?

**Comment by stripwax** [comment]
Mostly just the relationship or variation between the upstream SAASound and the bundled version (which is why I mentioned fork, specifically). For example, if there are any changes to CMakeLists.txt (and I see that there are), then it would be best to both 1. upstream those into my repo if these are changes everyone would benefit from and 2. manage those as commits in your fork if idiosyncratic to the bundling.

**Comment by simonowen** [comment]
I've removed the bundled version of the SAASound project and switched to using FetchContent to pull yours from GitHub. I prefer that to git sub-modules, which require more care on checking and for updates. It's automatically grabbed during CMake configure time for the SimCoupe project and cached for re-use.

I've set it to use your *current* head commit rather than always pulling HEAD from master, so I know exactly which version was included in which releases. For development you can update the commit hash to point at different versions, or a branch name. You can also change the repository URL to a local path containing your CMake folder and it'll use that instead. Feel free to send a pull request if you want the SimCoupe version advancing to include something new.

I hope that covers both of our needs -- thanks again for the library!
