### ISSUE TITLE
LYRA3.DSK is reported as invalid (worked ok on SimCoupe 1.0)

### ISSUE THREAD

**Issue by stripwax** [simonowen/simcoupe#32]
Actually there seems to be a bunch that are no longer working, that previously used to work.   The error message doesn't say much though.  e.g.  "Invalid disk: G:\GAMES\emu\Sam Coupé\disks\ASTROB.DSK" .  I've not yet found a pattern, although these are pretty old DSK files.  Also seen with other format disks.  "Invalid disk: G:\GAMES\Emu\Sam Coupé\disks\HighColor.mgt" although for whatever reason "G:\GAMES\Emu\Sam Coupé\disks\tetris.dsk" loads fine

**Comment by stripwax** [comment]
Hm it seems like this could actually be broken "long filename" handling.  If I copy the same file to a different folder, they can be loaded ok :-)   Maybe it's choking on the é?  These used to work fine in this folder though :-)

**Comment by simonowen** [comment]
I think it might be broken utf-8 handling somewhere, as adding an accented character to either the path or the filename breaks things. I fixed an issue a few months back in the same area, so either that's not made it to the main branch or I've unknowingly introduced another one. I've started using a 3rd party std::filesystem in more places, so it could be there.

I'll check in detail over the weekend -- thanks!

**Comment by simonowen** [comment]
Fixed in 5597488b237217c5e7267e195b9f9e4227526d2f in the dev branch.

As suspected it was an encoding issue, with paths passed around in native format (default Windows codepage), but some library components expecting them to be utf-8. Until everything is moved over to work in the same encoding (likely utf-8) there could be some related bugs. The change should be enough to fix your path issue.
