### ISSUE TITLE
Recording video seems broken

### ISSUE THREAD

**Issue by stripwax** [simonowen/simcoupe#42]
Recording .gif seems to capture only around the top third or half of the screen.  Recording .avi seems to create an unplayable video. Note that I have not used either of these functions before, so maybe this is expected, but seems faulty to me.

**Comment by simonowen** [comment]
The GIF issue sounds the same as #38, which is fixed in the `dev` branch.  That'll be part of the next release when I've fixed some of the outstanding issues.

I've tried the AVI recording with the 20200827 build and it's working for me in both full size and half size modes. I suspect the video player doesn't support the video format. SimCoupe encodes the video using the MS-RLE format, which is an old lossless palettised format. Ironcally, Microsoft no longer supports it in the built-in Windows 10 video player, but it used to work in the older Windows Media Player. It still plays fine in VLC (possibly thanks to our own Frode Tennebø for bug fixing it when they broke it), and still works fine as a YouTube upload. 

MS-RLE was appealing at the time as it was fairly widely supported for playback and gave small lossless video files. It was also easy enough to implement directly in SimCoupe, so it worked across all platforms with no extra effort. It may now be better to use a 3rd party library for the video encoding to give a choice of encoding format. It's likely we have spare cores to spend more time encoding and the output file size is less of a concern than it was.

I think that covers the reported issues, but if you think I've missed something please re-open!

**Comment by stripwax** [comment]
Understood, I didn't check the closed issues. Thanks
