### ISSUE TITLE
SimICE: show labels in trace

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#43]
The trace is fantastic. It would be even better if the labels could be shoehorned into the limited space somehow.

**Comment by simonowen** [comment]
I've increased the debugger width to allow some space for symbols instead of addresses. There isn't room to allow symbols in the disassembly part of the view, to leave space for register differences:

![image](https://user-images.githubusercontent.com/200089/125352434-29ee2700-e359-11eb-97a7-387bdd0ff07a.png)

The extra space also allowed the visible label length to be increased from 19 to 25, and I know you like your long labels! If the disassembly view is too spaced out now I could reduce how much space it uses. The text and hex views are the same width, with only the graphics view making use of the extra space.

The fixed width font in the current debugger uses too lots of space for labels. That'll only improve when the debugger is eventually moved out to a native window.
