### ISSUE TITLE
SimCoupe.exe flagged as virus

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#51]
Since today Microsoft Defender is flagging SimCoupe.exe as a virus:

````
TrojanDropper:Win32/Stioldaat.STB

Alert level: Severe
Status: Active
Date: 2021-05-27 22:59
Category: Trojan Dropper
Details: This program is dangerous and installs other programs.

Affected items:
  file: C:\Program Files (x86)\SimCoupe\SimCoupe.exe
````

**Comment by simonowen** [comment]
I ran into the same thing last night so it seems to be yesterdays definition update that triggered it. Running it through virustotal.com had a couple of other engines flagging it too, so maybe there's a loose heuristic match being shared around. I've reported it to the other engines as a false-positive but it'll probably take time for them to check and white-list it. That said, when I checked at lunchtime today the Microsoft scanner was no longer showing it as infected, so hopefully the Windows Defender definitions for Windows 10 get the same update soon.

I used to have problems with UPX-compressed files spooking virus scanners, even though the EXE compression was completely reversible. It was enough to make me stop using it. I don't know what they don't like about the module. It doesn't perform any network comms, and the most I can think it does is use ShellExecute to launch the website and help file!

The disappointing thing is that the EXE is code-signed, so I know it hasn't been modified since I built it. It's a 5 year old code-signing certificate that has been used on plenty of executables during that time. At one point it was supposed to help with reputation in situations like this, but maybe only the expensive EV certificates (not available to individual developers) count towards that now.

If it's still not fixed by tomorrow I'll experiment with rebuilds to see whether removing certain function calls changes it. I'll leave the issue open until the Windows Defender definitions fixes the original, just in case anyone else comes to report it. Thanks Stefan!

**Comment by simonowen** [comment]
I think today's Windows Defender definition update (1.339.1550.0) stops it being seen as a threat. I had to manually force the update to get the new definitions, but after that I copy the EXE without issue. Does that work for you too?

However, it looks like they've just allowed that specific file. Building a new version from the same source causes it to be seen as the same threat. I really don't want to have to submit each new EXE for false-positive testing, so I might reduce the frequency of x86 builds. The x64 builds are fine, and I'd guess most users are using a 64-bit OS anyway.

**Comment by simonowen** [comment]
New builds are still detected by the very latest 1.339.1577.0 definitions. I'll keep hitting them with samples until it's resolved.

However, submitting a new build to virustotal.com has only the Microsoft scanner now [unhappy](https://www.virustotal.com/gui/file/f34051bbe9a7b7ab4b2f952551c9646bd2abc93cd5f874cceaeea3d255bca1be/detection) with it. It's hard to know if the others have improved the scanning or I've just been lucky.

**Comment by stefandrissen** [comment]
> I think today's Windows Defender definition update (1.339.1550.0) stops it being seen as a threat. I had to manually force the update to get the new definitions, but after that I copy the EXE without issue. Does that work for you too?

I had already added it to the allowed threat list or so.

> However, it looks like they've just allowed that specific file. Building a new version from the same source causes it to be seen as the same threat. I really don't want to have to submit each new EXE for false-positive testing, so I might reduce the frequency of x86 builds. The x64 builds are fine, and I'd guess most users are using a 64-bit OS anyway.

Where can I find these x64 builds you speak of? Both the .exe installer and the .zip in the [releases](https://github.com/simonowen/simcoupe/releases) are 32-bit - I do not think I've ever see an x64 build of SimCoupe.

**Comment by simonowen** [comment]
I don't think I'd ever officially released an x64 Windows build, though it's what I usually use during development. It's generally a little faster than the equivalent x86 version, though speed hasn't really been an issue for a while. In fact I'm trying to simplfy some areas of the code at the moment that will be at the expensive of some optimisations, which will reduce the maximum speed.

I've refreshed the binary files for the last release on GitHub to avoid most false-positives (except 1 on the installer), which should cover this issue. I've also added in a 64-bit zip if you want to give it a try. It should work just the same as the 32-bit, using the same options files.
