### ISSUE TITLE
[question] OpenGL requirement

### ISSUE THREAD

**Issue by cmitu** [simonowen/simcoupe#52]
Hi,

after https://github.com/simonowen/simcoupe/commit/1769d19117e7111fbbfb74789005a5b8b4d962c8, if OpenGL is detected at build time, it's automatically set as the renderer backend (via `HAVE_OPENGL`). This poses an issue when - at runtime - the running system either doesn't support OpenGL or doesn't support the version asked (3.3 core). As an example, a Raspberry PI system (or pretty much any ARM SBCs) doesn't support OpenGL 3.3, though it supports OpenGLES (2.0 for models < 4 and 3.1 for the Pi 4 model).

 Is using OpenGL is not a a hard requirement, I could provide a patch for the `cmake` build files that could disable OpenGL at build time (as an option) and would allow the usage of SDL's software/opengles renderers for systems where OpenGL 3.3 is not supported.

**Comment by simonowen** [comment]
If OpenGL is detected at build time it favours using it at runtime, but it'll fail if 3.x isn't available. If that happens it should fall back to using the generic accelerated surface support in SDL. `UI::Init()` in SDL/UI.cpp tries both:

```c++
#ifdef HAVE_OPENGL
    if (auto backend = std::make_unique<SDL_GL3>(); backend->Init())
    {
        return backend;
    }
#endif

    if (auto backend = std::make_unique<SDLTexture>(); backend->Init())
    {
        return backend;
    }

    return nullptr;
```

Is it possible that both are failing? I don't think I've tried to build the Pi version since those changes, but I remember manually checking that the fallback method worked under Windows.

I did start working on an equivalent OpenGLES backend but I think the 8-bit texture support (internal_format=GL_R8, format=GL_RED, type=GL_UNSIGNED_BYTE) wasn't available, and that's used to colour-space convert from the palettised SAM format to the RGB output. I suppose it's possible the same limitation causes the fallback SDL backend to fail.

Longer term I was hoping to drop the SDL texture backend in favour of something more generic like Vulkan, even if that limited it to the Pi 4 or later. I'm looking to replace the built-in GUI elements with Dear ImGui, which will need to know more about the underlying graphics context than the SDL texture approach provides. I do need a working Pi alternative before that can happen.

**Comment by cmitu** [comment]
Thank you for the response.

> Is it possible that both are failing? I don't think I've tried to build the Pi version since those changes, but I remember manually checking that the fallback method worked under Windows.

I don't recall the exact error message, but I'll give it a test later on and report back. 
This was on a Pi3 which doesn't have (OOB) OpenGL support, I think it worked on the Pi4 (since it supports OpenGL 2.1 with the Mesa drivers), but I can test that also.

**Comment by simonowen** [comment]
It looks like the fallback backend is broken because the SDL environment is poisoned by even trying OpenGL. Adding a call to `SDL_GL_ResetAttributes()` to the end of `SDL_GL3::~SDL_GL3()` cleans it up so the fallback works. There's a secondary issue of it picking a software OpenGL 3.x implementation on Pi 3 or earlier. I should be able to check for MESA acceleration and fail if it's running in software, again to give the fallback.

Unrelated to that, my development branch recently switched to a more accurate Z80 core, which lost some cache/table optimisations. That drops performance to around *half*, so even the Pi 4 isn't able to run at full speed (90-95%). I'll need to address that before it gets merged into master! I'll commit the OpenGL fixes direct to master when I have them.

**Comment by simonowen** [comment]
I think the commit should fix the reported issue -- please re-open if I've missed anything!

**Comment by cmitu** [comment]
I tested on a Pi4 and a Pi3 and it's ok.
Thank you for the fast response.
