### ISSUE TITLE
SimICE: Bad step of instructions with index register.

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#53]
It seems that the instruction is performed corect and the error is only in the view.
It's the same in Trace.

**Comment by simonowen** [comment]
This was caused by the change of CPU core, which was allowing breakpoints and tracing to be processed after just the index prefix. I've made a change that restores the old correct behaviour.  Thanks for the report!

I also noticed that step-out in the debugger was broken due to a missing CPU hook. I'll create an updated dev version with these fixes in the next few days.

**Comment by simonowen** [comment]
Fixed in the new [dev build](https://github.com/simonowen/simcoupe/releases/tag/20210707).
