### ISSUE TITLE
Recording problem.

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#58]
Save failed for AVI, GIF, WAV and PNG.
Only SSX saved successfully.

**Comment by simonowen** [comment]
They're all working here for me in v1.2.2. The code that generates a unique filename and opens it is very similar for the working and non-working formats.

Does it report any error when starting or ending a recording?

If you visit `%APPDATA%` in Windows Explorer, does the path contain any accented characters?

**Comment by AntonyDTA** [comment]
It reports this error when starting the recording. (Instead of recording.)
File path is equal for saved and failed format.

![SaveFailed](https://user-images.githubusercontent.com/68946405/127962361-5500958e-28b8-47d5-946c-ee0e66e6523e.png)
![Saved](https://user-images.githubusercontent.com/68946405/127962388-bf37e7ae-9de8-4d78-8d27-3af089fc7414.png)
[SimCoupe_cfg.zip](https://github.com/simonowen/simcoupe/files/6921252/SimCoupe_cfg.zip)

**Comment by simonowen** [comment]
The paths all look well formed and simple, and the initial file creation is almost identical between avi and ssx.

Do you have an anti-virus program that could be protecting media file types? It seems curious that types such as avi/png/gif/wav are failing but an unknown type like ssx succeeds.

**Comment by AntonyDTA** [comment]
My previously used SimCoupe v1.1 (20210501) works perfectly for AVI, GIF, PNG, SSX.
WAV has some problem with stop recording but saved.
For WAV recording i used even older version.

**Comment by simonowen** [comment]
One difference between those versions is the code signing certificate used to sign the EXE. My old certificate expired in May 2021 and the 20210501 release is the last version signed using it. Later builds are signed with the new certificate, which starts off with no reputation and may take time before it's trusted.

It still feels like some anti-ransomware component could be protecting certain file types when it doesn't yet trust. I know Windows 10 has Ransomware protection but it looks like you're using Windows 7? The media saving code in SimCoupe hasn't changed since August 2020 so I don't think it's a new/recent bug.

Here are some new builds of SimCoupe from the same source code as v1.2.2, but with the media file extensions changed. I've changed the first character of each extension to 'x', so PNG will save as .xng, etc.  Is it able to save files now?

[SimCoupe-v1.2.2.media_win_x86.zip](https://github.com/simonowen/simcoupe/files/6923746/SimCoupe-v1.2.2.media_win_x86.zip)
[SimCoupe-v1.2.2.media_win_x64.zip](https://github.com/simonowen/simcoupe/files/6923747/SimCoupe-v1.2.2.media_win_x64.zip)

If you're able to try both 32-bit and 64-bit, do they behave the same?

**Comment by simonowen** [comment]
Windows 10 has this Ransomware protection:

![image](https://user-images.githubusercontent.com/200089/128010160-de84bf02-8b71-4f28-9d7a-d55a0eaea320.png)

The folders it covers by default includes Documents.  If you have that feature, try looking under Block History to see if SimCoupe is listed there.

**Comment by simonowen** [comment]
I've reproduced your issue symptoms with the 'Ransomware protection' enabled. It was previously disabled -- I'm not sure if I changed the setting or if it was off by default.

![image](https://user-images.githubusercontent.com/200089/128010867-b19426d7-5ee3-408f-aa5b-4c1c2b282b5e.png)

Under the _Actions_ menu I was able to allow it on the current device, then saving worked again. Seems like code signing is becoming increasingly worthless  :(

**Comment by AntonyDTA** [comment]
My system is not quite right. I don't want to update it. I think I'll change it to Linux.
It seems to be just my problem, you can close this issue.

**Comment by simonowen** [comment]
Thanks for the report anyway!  I always prefer to look into potential issues in case there's something deeper causing it.  :)

I wondered if I could improve the diagnostics for failed saves.  On my system under this key:
HKLM\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Controlled Folder Access
there's an "EnableControlledFolderAccess" value that is non-zero if folder protection is enabled.

I thought I might be able to check that value in SimCoupe after any file creation failures, to give users a hint about what might be wrong. Though it looks like the key isn't visible to most processes due to strict security permissions. On the plus side, the protection feature is currently disabled by default and should generate a desktop popup when an application is blocked.
