### ISSUE TITLE
debugger: show raster position in real time on breakpoint

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#6]
When the debugger is enabled a dot is shown indicating the current raster line position. This is very cool. But, I'd like to add a breakpoint on writes to port 232 (bpio e8 w) and just let simcoupe continue at full speed so that I watch the output and visually check the timing of my mod player code.

Currently I can do this in by stopping at each breakpoint - but comparing 208 dots at two approximate horiziontal positions is a bit tedious.

**Comment by stefandrissen** [comment]
I would like the breakpoints to act as visual "break points" only - ie the "breakpoints" show the raster dot when their condition is met, but do not stop the emulator.

It would then look something like:

![simc0028](https://user-images.githubusercontent.com/5297464/46417895-dd4a7b80-c72a-11e8-98a7-00d449685898.png)

With the dots jumping around a bit due to when the interrupts get a chance to cut in.

**Comment by simonowen** [comment]
It might be difficult to achieve that with the current code, which conditionally draws the dot when the emulation is stopped part way between frames when the debugger GUI is active.  It's drawn just after the last displayed pixel, so it's automatically overwritten by the next SAM display drawing.  Drawing one pixel back would leave a trail on the display, which is kind of what you want, but would also affect single-stepping.  Skipping a pixel isn't easy as all the display code works in strips of 8 pixels.  Also, the debugger doesn't currently have a concept of actions for breakpoints, which would be needed to continue running.

Better diagnostics and easier debugging is definitely an area that could benefit from enhancement in SimCoupe, since the emulation side is largely a solved problem. I'll have to think if there's a more general approach to capture and expose the sort of detail you're after.

I've previously considered optional diagnostics through special instructions.  Overloading the useless LD r,r patterns would give 1-byte access to various actions, which could include palette colour cycling, counter incrementing/resetting, etc. The down side would be that it still has a timing cost to include in code, due to the contended memory fetch.  It would probably still work well enough for many situations, perhaps including what you're after now.  What if a LD H,H instruction could be made to cycle palette 0 to the next colour in a sequence?  It wouldn't have the same I/O contention hit as your own palette output mode (due to the F8-FF port range attracting the attention of the ASIC).  It could also be replaced by a NOP in final code, which would have identical timing but without the side-effects (which would be turned off by default in SimCoupe, of course).

The other option is to build a special version of SimCoupe that does what you want, and use it just for this task.  That does feel like cheating though, but I've use that approach plenty of times before  :)

**Comment by stefandrissen** [comment]
Hmm... I thought it would be an easy option, and since it's not, I agree that a more general (long term) approach is the way to go.

Thanks for your input.
