### ISSUE TITLE
Status port does not always indicate frame interrupt

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#60]
Another very strange issue here. 
- Double click on the attached lllll.frame-interrupt.dsk
- SimCoupe 1.2.2 is started and disk is booted
- Code keeps looping around in IM1 interrupt handler waiting for a frame interrupt, which it is detecting using the status bit (bit3), but it is **never** set:

![image](https://user-images.githubusercontent.com/5297464/129267192-28c42578-81eb-416f-8455-ac556da2d079.png)

If I reset SimCoupe (F12) and reboot, all is fine.
If I first start SimCoupe, select disk image and boot, all is fine.

[lllll.frame-interrupt.dsk.zip](https://github.com/simonowen/simcoupe/files/6978475/lllll.frame-interrupt.dsk.zip)

**Comment by stefandrissen** [comment]
Well, this is embarrassing. The status register indicates the interrupt with a **low** bit.

> Bit 0 LINE int when low, signals the line interrupt register is requesting.
> Bit 1 MOUSE int when low, signals the mouse requests the interrupt.
> Bit 2 MIDIIN int when low, signals the MIDI channel has a data byte.
> Bit 3 FRAME int when low, signals the frame scan has been completed (50 per/second).
> Bit 4 MIDOUT int when low, indicates the NrDr out register has just completed data output. 

I just now have no clue why how the image is booted is making a difference nor how my code has worked until now...

**Comment by simonowen** [comment]
I can see something odd in SimICE that I don't yet understand.  The frame end event is showing up unexpectedly, as though an interrupt has just been triggered. Though the events show the next frame interrupt is almost a full frame away. It does feel like an issue with the initial state, which is fixed by a reset.  I'll investigate later!

**Comment by simonowen** [comment]
I was mistaken in what I saw earlier. It was just the single-step on the HALT causing it to skip ahead to when the interrupt handler was entered. So it really was the next frame interrupt triggering normally, even though it appeared to be looping very quickly.

I'm about 90% sure it's a timing issue, which is hit every time by the auto-boot because the sequencing is completely deterministic. If I start the CPU cycle counter at 50000 (roughly half way through a frame) instead of 0, the auto-boot works. The timing from power-on in previous versions might be slightly different, and enough to make a difference here. I could randomise the starting cycle count, but it's probably better that the behaviour is the same each time to help understand what's happening -- for both of us!

I noticed that in the stuck boot case a `bpx 2:335` was hit only once. Under the same conditions the `cp (hl)` target location wasn't being written to by anything, so it was never going to exit the loop. It seems like a deadlock between the interrupt and non-interrupt code, but I don't understand what it's doing well enough to suggest anything to help.

**Comment by stefandrissen** [comment]
In hindsight, my code should never have worked. 

It is trying to approximate 60 Hz sound playback by combining frame and line interrupts. 
The first expected interrupt is a line interrupt, but this is never set by my code.

**Comment by simonowen** [comment]
I needed a 60Hz event for the SID player, which ended up using a mix of frame, midi and line interrupts. I've found a [test program](https://github.com/simonowen/simcoupe/files/6981945/60hz.zip) I wrote for it, which doesn't work in recent versions of SimCoupe, so _something_ is broken. It might be affecting your code that is trying to do the same.

I knew major refactoring might be a risk but it's creating more subtle issues than I expected. I'll be glad to get some unit tests in place!

**Comment by simonowen** [comment]
Plot twist: the test program shouldn't have worked, and it's the old version of SimCoupe that is wrong!

The test program chains 10 MIDI OUT interrupts together to get to one of the required synchronisation points for 60Hz. The first interrupt is triggered correctly, but when it writes a MIDI byte for the second interrupt it's ignored. I can see a MTXF (MidiTxfmstEnd) event in the queue in SimICE, showing the MIDI hardware is still busy and not ready to accept new data. If the test program had checked the TXFMST bit in LPEN it would have seen that.

Older versions of SimCoupe the reset the TXFMST bit as part of triggering the MIDI OUT interrupt, which was wrong. That meant they would accept new data as soon as the interrupt handler was executed. I added some new tests to my ASIC test program and improved the emulation in that area. The test program doesn't work on real hardware and the newer SimCoupe versions are correct.

**Comment by simonowen** [comment]
Am I safe to close this, or do you still think there's a SimCoupe issue?

**Comment by stefandrissen** [comment]
Definitely, my current code is bananas.

**Comment by stefandrissen** [comment]
And I think I've finally figured out what my problem is, after setting a line interrupt the line interrupt was not triggering. It turns out that this is a result of samdos enabling samrom interrupts which are setting palette and line interrupts for palette changes (for ``palette a,b line y`` handling). Since there are none, line interrupts are disabled (set to 0xff). Grrr....
