### ISSUE TITLE
SimCoupe hangs when /removing/ usb headphones

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#7]
Windows 10x64 [10.0.17134.285]
SimCoupe v1.1 alpha

When _removing_ my usb headphones, SimCoupe hangs.
Inserting my usb headphones is not a problem.

**Comment by simonowen** [comment]
I suspect this is missing error handling when around filling the audio buffer.  If the active device is unplugged, all requests to it will be failed. The existing code ignores that and will wait forever for the required buffer space to be available.

It should probably react to GetCurrentPosition failing and call Init(true) to re-initialise audio.  If another audio device is available it'll use that, otherwise it'll fall back to timer-based 50Hz synchronisation.  It won't restore audio to the headphones if you plug them back in, but it's better than a hang.

I started changing the code from DirectSound to XAudio2, as DirectSound isn't as direct as it used to be on older versions of Windows.  I'll make sure it's fixed in that implementation.  Thanks for the report!

**Comment by simonowen** [comment]
This should be fixed by c92705435ab492fdbcc53d4232ae0ff487ac576b, which is part of the new [20200819 build](https://github.com/simonowen/simcoupe/releases/tag/20200819).

This changes the DirectSound backend to XAudio2 2.9. On Windows 8 and later it uses a virtual device endpoint that switches devices if they're unplugged. If it's still a problem please re-open.

**Comment by stefandrissen** [comment]
Confirmed fixed - thanks!
