### ISSUE TITLE
ROM V1.0 compatibility

### ISSUE THREAD

**Issue by dandoore** [simonowen/simcoupe#77]
1. Cannot load TZX tapes

I'm trying to load TZX tape images which are for ROM V1.0/SAMDOS 1.1 but issuing LOAD "" does not start the TZX player it just waits - ROM 1.0 tape trap different from later ROMs?

2. Booting SAMDOS v1.1 kind of works but corrupts the display:
![simc0072](https://user-images.githubusercontent.com/43847005/160417998-1a9c9929-d4e0-4d0e-9e2a-cab9ab1a022e.png)

Nothing here is really important - I only found it when trying to get some old SamTape images up and running!

**Comment by simonowen** [comment]
Both issues are caused by hard-coded hook addresses taken from the v3.0 ROM, which are almost certainly different in v1.0. Most other custom boot ROMs (such as Atom/AtomLite) are just simple patches on v3.0 so they'll be fine. I should be able to replace the fixed addresses with some code sniffing logic to check it's where each hook expects to be.

The tape hooks should really just be for convenience so I'll add buttons to start/stop the tape manually. There isn't really a work-around for 1) until the hooking is improved.

The corruption in 2) happens after it hits the NO DOS error hook, when it attempts to resume execution from BOOTEX in ROM1 after temporarily switching disk images. It's just jumping into the middle of nowhere and the corruption is just a side-effect of that. As a temporary work-around you can turn off the boot helper under in Tools -> Options -> Helpers -> "Allow booting from non-bootable disks". That'll give a normal NO DOS error instead, and with older ROM versions you'll have to use a CALL to finish booting DOS anyway.

While you're looking at tape images, I know of a different issue with some of the existing SAM tape dumps. You'll find some only load when tape traps are enabled in the Tape Browser, which means it'll pull in raw data from each block and adjust the registers to pretend it did it the slow way. Loading without traps will fail to load even the headers, so you won't see the filenames on screen. It seems to only affect tapes using "Standard Speed Data" blocks, with those using Turbo Speed Data still working fine. I suspect it's expanding to Spectrum-specific sync bytes instead of SAM ones, but I need to confirm that. I think it's an issue with the tape images, which might need converting/fixing to more accurately advertise what they hold.

**Comment by simonowen** [comment]
The new [v1.2.10](https://github.com/simonowen/simcoupe/releases/tag/v1.2.10) release should resolve these.
