### ISSUE TITLE
Beep command affected by emulation speed

### ISSUE THREAD

**Issue by Retrogamebloke** [simonowen/simcoupe#79]
I just noticed if I up the emulation speed it changes the beep commands to a higher pitch. Not sure now if it does this in regular Spectrum emulators, but pretty sure they tend to work ok.

Also if you enter a negative value directly in the editor it doesn't work.
So directly in without a line number
BEEP -3,1
will not play.
It works fine in a program though, just not as a direct command.
* ignore the last bit, seems I was getting the note and duration mixed up. The speed causing sounds to go higher pitched still stands, but as I say not 100% sure if that's just par for the course with emulation.

**Comment by simonowen** [comment]
SimCoupe stretches or compresses the audio to match the emulation speed, which will change the pitch. That's by design, and other emulators may choose to do it a different way.  There at least 3 ways audio can be treated at different emulation speeds:

1) At twice the emulation speed you could just drop half the audio samples _every frame_. If you drop the second half you'll retain the original frequency but introduce 50 audio join points per second, which is likely to add a buzz to the sound playback (try `BEEP 5,0` in different emulators at 200% speed). I think this is what you may be used to.
2) You can scale the audio samples, averaging or duplicating neighbouring samples to give the required sound duration. This changes the frequency but is how it sounds if you play audio at a faster or slower rate. It gives a smoother sound with no glitchy join points. This is what SimCoupe uses.
3) You can process the audio to carefully speed up playback without changing the overall frequency. It sounds less rough than option 1) but can still sound a bit choppy and unnatural, depending on the speed difference. I'm not sure whether this would be suitable for the low latency audio playback needed in emulators, but isn't something I've considered implementing.

I may try option 1) and see how it sounds in SimCoupe, and could make it an option in a future version.
