### ISSUE TITLE
publish windows binaries please

### ISSUE THREAD

**Issue by dddfffggg777** [simonowen/simcoupe#85]
publish windows binaries please

**Comment by dddfffggg777** [comment]
today

**Comment by simonowen** [comment]
The [Releases](https://github.com/simonowen/simcoupe/releases/latest) section always has the latest official Windows binaries, and I try to keep the [official website](https://simcoupe.org) synchronised with that.

There are automatic builds made for every published code change but the latest ones have now expired. I've just kicked off new builds and you can download the Windows version from the bottom of [this page](https://github.com/simonowen/simcoupe/actions/runs/3608435620).

I only recommend automatic builds if you really need fixes from the latest changes. They aren't code-signed like the official builds so Windows will show an unknown publisher warning when launching the installer version. They should still work the same and it's always worth raising new issue if you discover otherwise.

**Comment by dddfffggg777** [comment]
format b:
using "Pro-DOS-v2.dsk"
still gives error

**Comment by dddfffggg777** [comment]
the issue https://github.com/simonowen/simcoupe/issues/64

**Comment by dddfffggg777** [comment]
![simc0001](https://user-images.githubusercontent.com/114140927/205442337-018f2aa0-5578-4bc8-83cc-bfa872b05681.png)

**Comment by dddfffggg777** [comment]
![simc0000](https://user-images.githubusercontent.com/114140927/205442548-1bd5a3e3-6254-4516-9077-77b49c997507.png)
![simc0001](https://user-images.githubusercontent.com/114140927/205442555-e9888673-87a8-4602-ba0c-44a796e516b9.png)
