### ISSUE TITLE
Can't type colon in debugger

### ISSUE THREAD

**Issue by mikezt** [simonowen/simcoupe#90]
Hi!

I'm unable to type colon (:) in debugger. For example, I can't set breakpoint to second page with offset 0 (bpx 2:0).

**Comment by mikezt** [comment]
Sorry, I suck at bugreport. It seems it's only linux issue. I builded the emulator from latest git sources and I'm using Slackware 15. The issue is also the same on latest Debian.

**Comment by simonowen** [comment]
Thanks for the bug report!  The symbols usually come directly from SDL as part of the key events, which might mean they've changed how something is passed.

I've just built the SDL version under Windows and it's not working correctly for me either. I'm getting the symbols from the unshifted key instead. On my keyboard that means ";" instead of ":", and "," instead of "<" etc.  Is that the same effect you're seeing under Linux?

I'll look into it and see if I can work out which version of SDL introduced the changes, to try and stay compatible with all versions.  As a very short-term fix you could probably put a colon symbol on the clipboard and paste in with Ctrl-V where needed.

**Comment by mikezt** [comment]
Yes, it's the same behavior as I have. Thanks for the copy&paste tip, that's working and will do the job for now :-)

**Comment by simonowen** [comment]
Fixed in the latest v1.2.13 release.  Sorry it took so long to update!
