### ISSUE TITLE
Ambiguities of timing.

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#92]
Something is wrong, the values ​​obtained from SimCoupe do not match the values ​​from the table: https://simonowen.com/sam/timings/

Code=Ext: (in brackets are values ​​from SimCoupe)
Int->Int: Border 24/20 (24/19) , Screen 32/24 (32/27)
Ext->Ext: Border 21/16 (21/16 , Screen 21/16 (21/16) = OK
Int->Ext: Border 24/16 (24/19) , Screen 24/16 (24/19)
Ext->Int: Border 24/16 (24/19) , Screen 24/16 (24/19)

**Comment by simonowen** [comment]
The timings shown in the table are for two runs of exactly the same instruction type. The first instruction is used to align the start position for the timing, and the second instruction is the actual recorded timing. The table only works for unrolled blocks of exactly the same instruction. For other cases it's only an approximation of the timing, due to the variations in contention alignment, but should be close.

When neighbouring instructions are different types it's too complicated to be described by a single look-up table, especially if they access both internal RAM and I/O ports. The timing calculation will need to know the starting cycle number, the timings for each machine cycle of every instruction, where memory and I/O is accessed in the instructions, the type of memory and I/O port in each case. There's just too many parameters to be covered by a single static table.

Most of the values in the timing table will be a multiple of 4 due to the contention alignment positions. That will be true of any value in the first two columns, since internal memory fetches of the instruction bytes will align it.  Timings in the table that are not a multiple of 4 will be for instructions that don't access either internal memory or I/O, and in those cases the timings will match the official Zilog documentation timing values.

Your quoted SimCoupe timings are "unrounded", which suggests extra contention will be applied to execution of the _next_ instruction. Even a simple `LD r,n` instruction can be seen to take 7-16 cycles, where every timing value in that range is possible. The timing table shows the typical timings in each case, which for `LD r,n` will be 7 in external RAM or ROM, 8 in the border and 16 over the main screen.

**Comment by AntonyDTA** [comment]
I understand that, but somehow I forgot to mention that it is the LDIR instruction where I noticed it (LDDR will probably be the same). The difference is in the last pass, so the initial position is aligned. The time of the last pass is actually also the time of LDI (without repetition). My point is how much time will I save by replacing the LDIR with multiple LDIs. If the program will be in ROM and the LDIR transfer is from Int to Int, then for Border the table value is 20 and the value from SimCoupe debugger is 19, which is basically the same, but for Screen the table value is 24 and the value from SimCoupe is 27 and that there is already a difference. And the value from SimCoupe for LDI is 20(Border)/24(Screen), which corresponds to the table values.

**Comment by simonowen** [comment]
Thanks for the extra detail!  I definintely need to add an extra timing value to the table for the last loop iteration, where PC doesn't get adjusted for another loop.  I can repeat the table generation to check the specific case you mentioned.

Using LDIR in the ROM at 008F does help avoid the extra opcode fetch contention, so the only contention will be reads and/or writes from internal memory. Once aligned the instruction timings should be stable for the rest of the loop (which _should_ match the table values).  The last loop of LDIR will be interesting as the unrounded end of the instruction can overlap the RET instruction at 0091. If SP points to external RAM you will continue to avoid contention and should see the official 10T Zilog timing.

It'd be nice if the debugger could show the timing breakdown of instructions too. I'll have to look into that for the new debugger.

**Comment by simonowen** [comment]
I've just had a look in the debugger and everything is behaving as expected.  Here's a screenshot showing the LDIR executing in ROM, with HL and DE pointing to internal RAM, and the raster in the upper border. Each step of the loop is 24T, which matches the table:
![image](https://github.com/user-attachments/assets/11a75638-5804-4c52-bf18-f35f49aa6b2d)

After that if I set BC to 1 and step it will finish the LDIR instruction.  The instruction timing is now 19T, due to the 5T saving of not having to loop PC back to repeat the instuction:
![image](https://github.com/user-attachments/assets/59813e0e-e7f9-4a9d-be30-dff6bf5b9a7f)

However, this leaves the cycle count on an unrounded position that will be re-aligned on the next contended access. In this case it'll probably be when the following RET instruction accesses the stack in internal RAM, which may appear to take longer than expected.

To avoid hiding this penalty my timing measurement program re-executes the same instruction case to expose the extra delay. If I use the debugger to set BC=1 and PC=PC-2 and step the end of the LDIR loop a second time I get a timing of 20T, which is what is recorded in the table:
![image](https://github.com/user-attachments/assets/7c7e2138-cb2a-4e30-9be7-964eba16daab)

The timing for any instruction is affected by the cycle alignment after the previous instruction. Technically, the extra contention delay is part of the _next_ instruction, but since the delay could be 0-7 cycles you'd have to define each instruction time as a range, which wouldn't be very useful. Instead, I attempt to expose the hidden contention by counting it as part of the instruction that left the cycle counter misaligned. It won't be correct for all situations, especially if the opcode fetch of the next instruction isn't affected by memory contention (due to being in ROM or external RAM).

I'd use the timing table as a guide but you're much better benchmarking real code to measure timing, to account for the more complicated overlapping cases. I often set breakpoints at the start and end of test code and let it run, since the debugger will show the total cycle count since the debugger was last active. Or to look at simple cases you can do what I did here and do it all in the debugger, stepping to look at individual instruction timings.

**Comment by simonowen** [comment]
When I repeated the same test as above for the Screen area, the typical LDIR iterations were all 32T, matching the table. However the end of LDIR loop was 27T like you reported, even though re-executing the end of the loop showed 24T instead (matching the current timing table).  That sounds a lot like your reported issue!

It does seem like a case where attempting to include the hidden timing isn't working because of the adjusted start position. The end of loop will always follow the main loop, so it doesn't really make sense to re-align this case.  I'll look into updating the tables to reflect that.

**Comment by AntonyDTA** [comment]
Yes, that's the difference I noticed. I don't know what the real execution time of the last LDIR step is in the emulator, but in the debugger it shows a different value than in the table. I think the table is correct, but the debugger shows the wrong value. Since there is no LDI in the ROM, I checked the LDI from ExtMem and it was 24T, not 27T. And the last LDIR step should take exactly that long.

**Comment by simonowen** [comment]
I'd trust the debugger values more than the table, but be sure to single-step the LDIR more than once to get a true timing figure for each byte as the first byte will often be mis-aligned.

When the LDIR is running from ROM (or ExtRAM), HL and DE pointing to IntRAM, and the raster over the main screen it's 27T for the last iteration when BC=1. The timing table values are correct for the main execution of the instruction but not for the final loop of any of the block instructions -- I'll correct the table for those soon.

![image](https://github.com/user-attachments/assets/40e74203-f4ac-4bb4-ada1-742a7187adc3)

If your code is running in external RAM then an unrolled block of LDIs will be faster than using LDIR in the ROM. If your code is running from internal RAM, using unrolled LDIs is 4T faster in the border and the same over the main screen.

**Comment by simonowen** [comment]
I've updated the timing utility to run the block end test at the end of a normal loop execution, so it's naturally aligned. In all cases it gives a value 5T less than the non-end case, which is how long it takes to move PC back in the loop. This should more closely match the timings you see in the debugger, which were always correct.

The website timings now look like this:

![image](https://github.com/user-attachments/assets/e32a970c-e92b-4d6f-92c5-c938dd46c746)

![image](https://github.com/user-attachments/assets/a063652d-2e84-46dc-8780-6f20a8898ced)

Thanks for reporting this -- I think it better represents real cases. If there's anything you think is mismatched feel free to re-open this issue.

**Comment by simonowen** [comment]
I've also added an experimental instruction breakdown display as a mouse hover hint to all values in the timing table. They'll show more about what makes up the total timing. The item names are taken from the CPU emulation, though some are a bit general.

Here's an example showing an LDIR case that takes 32T over the main screen:

![image](https://github.com/user-attachments/assets/62b076f5-2491-4c52-b071-3e88e27624cf)

The main items of interest are `WAIT MREQ` and `WAIT IORQ`, which show memory and I/O contention delays. If there are no WAIT items listed then there are no additional delays during (repeated) execution.

**Comment by AntonyDTA** [comment]
So the time of LDI is less than the time of the last step LDIR ? I was under the impression that the LDI time is the aligned time of the last LDIR step.

**Comment by simonowen** [comment]
When the code is executing during the main screen drawing, the final LDIR step is slower than a single LDI, even if the LDIR is in ROM. Both LDI and LDIR have two memory accesses, but the positions inside the LDIR instruction are more costly due to their cycle alignment.

In general I'd expect unrolled LDI instructions to be faster as PC is already in the correct place for the next instruction. In LDIR it takes 5T to adjust PC back for each iteration.
